### ISSUE TITLE
因为html文件的原因，不支持pyinstaller打包

### ISSUE THREAD

**Issue by TotoroQwQ** [kwkwc/flask-docs#25]
大佬，一直在用你这个包。挺好用的。
最近想给项目用pyinstaller打包，打包没问题，运行时报文件找不到。
有没有动态加载路径的方法可以解决这个问题。
源码这个获取路径的方法，打包后找不到静态文件。
```
    APP_ROOT = os.path.dirname(os.path.abspath(__file__))
    APP_TEMPLATES = os.path.join(APP_ROOT, "templates")
```

**Comment by kwkwc** [comment]
你好，方便提供异常信息、路径示例、pyinstaller 命令参数等信息吗？

**Comment by TotoroQwQ** [comment]
> 

demo代码
![image](https://user-images.githubusercontent.com/8982154/226507170-3edf9a9e-5e2c-4c37-a707-31a35deb3c42.png)

打包：
pyinstaller -F demo.py

运行exe：
```
PS C:\Users\chenshi\Desktop\源码学习\flask-docs> .\dist\demo.exe
C:\Users\chenshi\AppData\Local\Temp\_MEI254122\flask_docs
Traceback (most recent call last):
  File "demo.py", line 2, in <module>
    from flask_docs import ApiDoc
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "flask_docs\__init__.py", line 38, in <module>
  File "flask_docs\__init__.py", line 44, in ApiDoc
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\chenshi\\AppData\\Local\\Temp\\_MEI254122\\flask_docs\\templates\\index.html'
[22280] Failed to execute script 'demo' due to unhandled exception!
```

**Comment by TotoroQwQ** [comment]
今天找到了一个解决方案，打包时，把flask_docs源码包也打包进去
```
pyinstaller --add-data "C:\Python310\Lib\site-packages\flask_docs;flask_docs" -F demo.py
```
这样运行exe就没问题了。

**Comment by kwkwc** [comment]
从报错信息看，路径没问题，原因是文件缺失，应该是打包的问题了

**Comment by TotoroQwQ** [comment]
> 从报错信息看，路径没问题，原因是文件缺失，应该是打包的问题了

是的，pyinstaller打包时，不会打包静态文件。好像只能打包时，将flask_docs源码及资源一起打包进去方便一点。
